[package]
name = "arachnid"
version = "0.1.0"
authors = ["Tim Mickel <tim@tmickel.com>"]

[dependencies]
reqwest = "0.9.10"
serde_json = "1.0"
serde = { version = "1.0.88", features = ["derive"] }
url = "1.7.2"